version: '3.8'

services:
  food-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///instance/local.db
    volumes:
      - ./instance:/app/instance
      - ./local_storage:/app/local_storage
    restart: unless-stopped 